find . -name '.*.swp' -exec rm {} \; -print ; vim .vim \
    Makefile \
    idebug.h \
    arrays.h \
    binary-search-trees.h \
    graphs.h \
    heaps.h \
    hashes.h \
    honors.h \
    intractability.h \
    llists.h \
    metas.h \
    parallel-computing.h \
    primitive.h \
    searches.h \
    sorts.h \
    stacks-queues.h \
    trees.h \
    tries.h \
    05-primitive-types.cc \
    06-arrays-and-strings.cc \
    07-linked-lists.cc \
    08-stacks-and-queues.cc \
    09-binary-trees.cc \
    10-heaps.cc \
    11-searching.cc \
    12-hash-tables.cc \
    13-sorting.cc \
    14-binary-search-trees.cc \
    15-meta-algorithms.cc \
    16-algorithms-on-graphs.cc \
    17-intractability.cc \
    18-parallel-computing.cc \
    25-honors-class.cc \
    README.txt
